### ISSUE TITLE
Add remainder in task and routine

### ISSUE THREAD

**Issue by mithun2022** [IvanHerreraCasas/flutter_planner#24]
daily planner app should have remainder functionality

**Comment by IvanHerreraCasas** [comment]
Hi, thanks for opening an issue.

Reminder functionality is certainly something that I'd like to add, my idea is to support reminders for event [activities](https://github.com/IvanHerreraCasas/flutter_planner/blob/main/packages/activities/activities_api/lib/src/models/activity.dart) (type 1), additionally, these could also be all-day events.

Let me know what you think, I'll try to work on this functionality this or next weekend.

**Comment by mithun2022** [comment]
That's good idea to add remainder for type 1 task but I think this willl be
good idea to add remainder functionality every task or routine if you have
enough time to do that.
Thank you

**Comment by IvanHerreraCasas** [comment]
Hi, sorry for the long wait, I was very busy but I have finally found some time.

As you can see in PR #28, I ended up adding reminders for all activities (including all-day), additionally, the events are now shown in the calendar to make it easy for the user to visualize them; for tasks, I added an option to show reminders for their remaining tasks (user can configure it in settings); and in the case of routines users can add it reminders when they are added to the daily activities, there are some cases that a routine will always require a reminder (like taking pills) and could be tedious to add it manually each time, but for those cases, it would be better other application rather than a daily planner, so I will not cover it.

And well that's all, again thanks for opening this issue and if you find some bug, please report it.
